"""Generate REPORT.md from whatever results exist — never hand-written.

The report is explicit about provenance: every table is stamped MEASURED,
x86 DEV PROXY, or PROJECTION so a reader can never mistake a projected number
for a measured one.
"""

from __future__ import annotations

import json
from pathlib import Path

from .llama_ingest import DECODE_TOL  # pre-registered decode noise band (±15%)

TAG = {"measured": "✅ MEASURED (on-silicon)",
       "roofline": "📐 ROOFLINE from measured microkernel ceilings (modeled tok/s — not real inference)",
       "dev": "🧪 x86 DEV PROXY (float, pipeline check — not Arm int8)",
       "projection": "📐 PROJECTION (published specs — run CI to measure)"}


def _load(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def _econ_table(rows: list[dict]) -> str:
    head = ("| instance | phase | i8mm | tok/s | tokens/$ | tokens/J* |\n"
            "|---|---|---|--:|--:|--:|\n")
    body = ""
    for r in rows:
        body += (f"| {r['label']} | {r['phase']} | {r['i8mm']} | "
                 f"{r['tok_s']:.1f} | {r['tokens_per_usd']:,.0f} | "
                 f"{r['tokens_per_joule']:.2f} |\n")
    return head + body


def generate_report(root: Path) -> Path:
    out = root / "REPORT.md"
    parts = ["# Tokonomics — generated report",
             "",
             "_This file is generated by `tokonomics report`. Do not edit by hand._",
             "",
             "`tokens/J*` carries a `*` because **power is never measured here** — "
             "it is TDP-derived from published specs. So a `tokens/J*` cell is a "
             "**projection even on a row whose throughput is `measured`**: the tok/s "
             "may be real silicon, but the joules are an estimate. Treat the energy "
             "column as directional, and rank instances by `tokens/$` (fully measured "
             "when CI runs) when you need a hard number.",
             ""]

    llama = _load(root / "results" / "measured" / "llama_economics.json")
    measured = _load(root / "results" / "measured" / "economics.json")
    dev = _load(root / "results" / "x86-dev" / "economics.json")
    proj = _load(root / "results" / "projected" / "economics.json")
    cross = _load(root / "results" / "projected" / "crossover.json")

    # Headline slot: real LLM inference (measured tok/s on a GGUF model). This is
    # the strongest evidence — measured throughput, not a roofline derivation —
    # so it leads the report the moment CI has run.
    if llama:
        lift = llama.get("i8mm_prefill_lift")
        dr = llama.get("decode_ratio")
        parts += [f"## {TAG['measured']} — real LLM inference (llama.cpp)",
                  f"Model: **{llama['model']}** on **{llama['instance']}** "
                  f"via `{llama['source']}`", "",
                  _econ_table(llama["rows"]), "",
                  (f"- **i8mm prefill lift: {lift:.2f}x** (measured pp512). "
                   f"**decode: {(dr - 1.0) * 100:+.0f}%** ({dr:.2f}x) — within the "
                   f"pre-registered ±{int(DECODE_TOL * 100)}% memory-bound noise "
                   "band, i.e. i8mm does **not** help decode (and the run is refused "
                   "if decode moves *with* i8mm beyond that band), exactly as the "
                   "roofline predicts. The macro (llama.cpp) run thus confirms the "
                   "micro (microkernel) ablation: i8mm pays off on prefill, not decode."
                   if lift is not None else ""),
                  ""]

    # Microkernel-derived economics. The int8 GEMM/GEMV ceilings and the STREAM
    # bandwidth are *measured* on silicon (`bench_off/on.json`: 85→101 GOPS,
    # ~34-35 GB/s), but the per-model tok/s below are a **roofline derivation** of
    # those ceilings onto this model — decode == prefill within an i8mm setting
    # because the simplified roofline applies one ceiling per setting. These are
    # modeled numbers, NOT a real-inference measurement; the measured per-phase
    # tok/s are the llama.cpp table above. This table is kept because it is the
    # microkernel→economics translation the reusable `action.yml` gate scores.
    if measured:
        # Drive the heading from the artifact's OWN kind so provenance lives in
        # the data, not in this layer — cmd_measured stamps it "roofline".
        mk = measured.get("kind", "roofline")
        parts += [f"## {TAG.get(mk, TAG['roofline'])}",
                  f"Model: **{measured['model']}** "
                  "— tok/s here are the **measured int8 ceiling projected onto the "
                  "model** (roofline), so decode == prefill within each i8mm "
                  "setting; see the real-inference table above for measured "
                  "per-phase tok/s.", "",
                  _econ_table(measured["rows"]), ""]

    for label, data in (("dev", dev), ("projection", proj)):
        if not data:
            continue
        parts += [f"## {TAG[label]}",
                  f"Model: **{data['model']}**", "",
                  _econ_table(data["rows"]), ""]

    if cross:
        winners = cross["winners"]
        if cross["has_crossover"]:
            # Name the actual winners pulled from the swept data so the prose can
            # never drift from the numbers: smallest ratio = most decode-heavy,
            # largest ratio = most prefill-heavy.
            decode_winner = winners[0]
            prefill_winner = winners[-1]
            verdict = (
                f"**No.** Decode-heavy traffic is won by **{decode_winner}** "
                f"(best bandwidth-per-dollar) and prefill-heavy traffic by "
                f"**{prefill_winner}** (best compute-per-dollar). Decode is "
                f"memory-bound, so its tokens/$ is flat — and even *declines* at "
                f"the newest chip — across generations (see the `decode` rows "
                f"above); `i8mm` lifts only `prefill` tokens/$ on each newer chip. "
                f"Where those two curves cross, the cheapest instance flips, so "
                f"the newest instance is *not* always the cheapest.")
        else:
            decode_winner = prefill_winner = None
            verdict = ("Yes — one instance stays cheapest across the swept range "
                       "(no crossover).")
        parts += ["## Crossover finding (projection)",
                  f"- prompt:gen ratios swept: {cross['ratios']}",
                  f"- tokens/$ winner per ratio: {winners}",
                  f"- **Is the newest instance always the cheapest?** {verdict}"]

        fm = cross.get("flip_margin")
        if fm and cross["has_crossover"]:
            parts.append(
                f"- **Flip margin (tightest cell):** at ratio {fm['ratio']}, "
                f"**{fm['winner']}** leads **{fm['runner_up']}** by only "
                f"**{fm['margin_frac'] * 100:.1f}%** — so *where* the flip lands "
                f"is input-sensitive (a small price/bandwidth change moves it), "
                f"even though *that* it flips is structural.")

        anc = cross.get("measured_anchored")
        if anc:
            survives = anc.get("survives")
            identical = anc.get("ordering_identical")
            afm = anc.get("flip_margin") or {}
            strength = ("**keeps the crossover and the identical per-ratio "
                        "ordering**" if identical else
                        "**keeps the crossover and the same decode/prefill "
                        "endpoint winners** (the flip ratio may shift)"
                        if survives else "**loses the crossover**")
            parts.append(
                f"- **Robustness — flip survives at MEASURED i8mm magnitude:** "
                f"rebuilding the sweep with on-ceilings pinned to this repo's "
                f"measured N2 uplift (**{anc['uplift']}x**, not the published ~2x) "
                f"{strength} "
                f"({anc['winners'][0]} decode-heavy → {anc['winners'][-1]} "
                f"prefill-heavy"
                + (f", tightest margin {afm['margin_frac'] * 100:.1f}%" if afm else "")
                + "). The flip is set by bandwidth-per-$ vs compute-per-$, so its "
                "existence does not depend on the optimistic 2x — only on the "
                "i8mm uplift being >1, which the measured run confirms.")

        parts += ["",
                  "> Sensitivity: this is a **projection** computed from the "
                  "hand-entered `projection/specs.yaml` (bandwidth, peak GOP/s) and "
                  "`econ/pricing.yaml` ($/hr, TDP). The crossover *ordering* is "
                  "robust (compute-per-$ rises while bandwidth-per-$ is flat), but "
                  "the exact ratio where it flips — and whether decode tokens/$ "
                  "strictly *declines* at the newest chip — depends on those "
                  "inputs. Re-run CI with measured ceilings to confirm on silicon.",
                  "",
                  "![crossover](figures/crossover_projected.png)",
                  ""]

    if measured is None and llama is None:
        parts += ["## Measured Arm numbers",
                  "_Empty until the CI harness runs on real silicon "
                  "(`.github/workflows/bench.yml`, free `ubuntu-24.04-arm` = "
                  "Neoverse N2). Fork and run it to populate this section with "
                  "your own measurements — both the microkernel ablation "
                  "(`tokonomics measured`) and the real-model llama.cpp run "
                  "(`tokonomics llama`)._", ""]

    out.write_text("\n".join(parts), encoding="utf-8")
    return out
